version: "3.7"  # optional since v1.27.0
services:

  based:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /home/fabian/Descargas/SIGMA/Base_Datos:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: sigma

  grafo:
    image: phpmyadmin:5.1.3-apache
    environment:
      PMA_HOST: based
    ports:
      - 7000:80

  sitio:
    build: . 
    ports:
      - 7001:80
    volumes:
      - /home/fabian/Descargas/SIGMA/WEB/:/var/www/html
      
      



#docker-compose -p sgm up --build

## Para Iniciar los contenedores
## cd /home/fabian/Descargas/SIGMA/_Espacio_trabajo/
## docker-compose -p sgm up -d
      
## docker exec -it sgm_sitio_1 bash

## Parar el servicio: 
## docker-compose -p sgm down